# Generated by Django 4.1 on 2022-08-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('Overview', models.TextField(blank=True, max_length=1000)),
                ('price', models.IntegerField()),
                ('imagesMain', models.ImageField(upload_to='photos/product')),
                ('images1', models.ImageField(upload_to='photos/product')),
                ('images2', models.ImageField(upload_to='photos/product')),
                ('images3', models.ImageField(upload_to='photos/product')),
                ('Days', models.CharField(max_length=100, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('No_of_peoples', models.CharField(max_length=100)),
                ('inclusion', models.TextField(max_length=500)),
                ('exclusion', models.TextField(max_length=500)),
                ('things_to_pack', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.category')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_name', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=165)),
                ('description', models.TextField(max_length=500)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.packages')),
            ],
        ),
    ]
