# Generated by Django 4.1 on 2022-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_packages_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
