# Generated by Django 4.1 on 2022-08-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_packages_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
