# Generated by Django 4.1 on 2022-08-30 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_packages_date_packages_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.packages'),
        ),
    ]
