# Generated by Django 4.1 on 2022-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_itinerary_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Days',
            field=models.CharField(max_length=100),
        ),
    ]
