# Generated by Django 4.1 on 2022-08-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_packages_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.packages')),
            ],
        ),
    ]
