# Generated by Django 4.1 on 2022-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebooking',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='variations',
            name='variation_category',
            field=models.CharField(choices=[('No_of_peoples', 'No_of_peoples'), ('No_Days', 'No Days')], max_length=100),
        ),
    ]
