# Generated by Django 4.1 on 2022-09-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_datebooking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
