# Generated by Django 4.1 on 2022-09-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_packages_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebooking',
            name='Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
