# Generated by Django 4.1 on 2022-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_datebooking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebooking',
            name='isbooked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
