# Generated by Django 4.1 on 2022-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_datebooking_isbooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
