# Generated by Django 4.1 on 2022-09-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorz', '0009_adverstisement'),
        ('trips', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorz.registrationz'),
        ),
    ]
