# Generated by Django 4.1 on 2022-10-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_packages_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebooking',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
