# Generated by Django 4.1 on 2022-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_datebooking_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Overview',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='packages',
            name='exclusion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='packages',
            name='inclusion',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='packages',
            name='things_to_pack',
            field=models.TextField(max_length=2000),
        ),
    ]
