# Generated by Django 4.1 on 2022-08-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='mobile',
            new_name='phone',
        ),
    ]
