# Generated by Django 4.1 on 2022-08-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('company_logo', models.ImageField(upload_to='photos/vendor')),
                ('owner_name', models.CharField(max_length=500)),
                ('adhar_no', models.CharField(max_length=500)),
                ('aadhar_image', models.ImageField(upload_to='photos/vendor')),
                ('office_address', models.TextField(max_length=1000)),
                ('mobile', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('registration_doc', models.ImageField(upload_to='photos/vendor')),
                ('licence_no', models.CharField(max_length=500)),
                ('licence_image', models.ImageField(upload_to='photos/vendor')),
                ('year_of_experience', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('appProcess', models.CharField(choices=[('Registration_Approved', 'Registration_Approved'), ('Under_Process ', 'Under_Process'), ('Approved', 'Approved')], default='Registration Approved', max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
