# Generated by Django 4.1 on 2022-08-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationz',
            name='confirm_password',
        ),
    ]
