# Generated by Django 4.1 on 2022-08-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorz', '0004_alter_registrationz_appprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationz',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='registrationz',
            name='email',
            field=models.EmailField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationz',
            name='mobile',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
