# Generated by Django 4.1 on 2022-08-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorz', '0005_remove_registrationz_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationz',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registrationz',
            name='mobile',
            field=models.CharField(max_length=500),
        ),
    ]
