# Generated by Django 4.1 on 2022-08-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorz', '0007_alter_registrationz_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationz',
            name='adhar_no',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='registrationz',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
