# Generated by Django 4.1 on 2022-09-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorz', '0008_alter_registrationz_adhar_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverstisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/add')),
                ('image2', models.ImageField(upload_to='photos/add')),
                ('image3', models.ImageField(upload_to='photos/add')),
            ],
        ),
    ]
