# Generated by Django 4.1 on 2022-09-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_datebooking_date_and_more'),
        ('payment', '0002_remove_order_order_package_order_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerdetails',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.packages'),
        ),
        migrations.DeleteModel(
            name='OrderPackage',
        ),
    ]
