# Generated by Django 4.1 on 2022-09-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_datebooking_date'),
        ('payment', '0006_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.datebooking'),
        ),
    ]
