# Generated by Django 4.1 on 2022-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(null=True),
        ),
    ]
